# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: bioconda
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## conda-forge packages
  - conda-forge::python=3.7.6
  - conda-forge::markdown=3.2.2
  - conda-forge::r-base=3.6.3
  - conda-forge::r-optparse=1.6.6
  - conda-forge::r-rcolorbrewer=1.1_2
  - conda-forge::r-reshape2=1.4.4
  - conda-forge::r-ggplot2=3.3.2
  - conda-forge::r-tidyr=1.1.0
  - conda-forge::r-scales=1.1.1
  - conda-forge::r-pheatmap=1.0.12
  - conda-forge::r-lattice=0.20_41
  - conda-forge::r-upsetr=1.4.0
  - conda-forge::r-xfun=0.20
  ## bioconda packages
  - bioconda::bioconductor-deseq2=1.26.0
  - bioconda::bioconductor-phyloseq=1.30.0