install.packages("tidyverse")
install.packages('vegan')
install.packages('ggplot2')
install.packages('plotly')
install.packages('DESeq2')
install.packages('phyloseq')
install.packages('reshape2')
install.packages('plyr')
