install.packages("tidyverse")
install.packages("rmarkdown")
if (!requireNamespace("BiocManager", quietly = TRUE))
   install.packages("BiocManager")
BiocManager::install("DESeq2")
install.packages('vegan')
if (!requireNamespace("BiocManager", quietly = TRUE))
   install.packages("BiocManager")

BiocManager::install("phyloseq")
install.packages('ggplot2')
install.packages('plotly')
install.packages('reshape2')
install.packages('plyr')
install.packages('dplyr')
install.packages("scales")
install.packages("comprehenr")
install.packages("ggpubr")
install.packages("hash")
install.packages("ggrepel")
install.packages('dplyr')
install.packages('ALDEx2')